// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tixora.Infrastructure.Data;

#nullable disable

namespace Tixora.Infrastructure.Migrations
{
    [DbContext(typeof(TixoraDbContext))]
    [Migration("20260403082117_RenamePartnershipTeamUser")]
    partial class RenamePartnershipTeamUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tixora.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.BusinessHoursConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("BusinessHoursConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            DayOfWeek = 0,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsWorkingDay = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsWorkingDay = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsWorkingDay = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsWorkingDay = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsWorkingDay = true,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(0, 0, 0),
                            IsWorkingDay = false,
                            StartTime = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            DayOfWeek = 6,
                            EndTime = new TimeOnly(0, 0, 0),
                            IsWorkingDay = false,
                            StartTime = new TimeOnly(0, 0, 0)
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.DelegateApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DelegateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PrimaryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DelegateUserId");

                    b.HasIndex("PrimaryUserId", "DelegateUserId", "IsActive");

                    b.ToTable("DelegateApprovers");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("TicketId");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000001"),
                            Alias = "AAI",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Al Ain Insurance"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000002"),
                            Alias = "DIB",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dubai Islamic Bank"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000003"),
                            Alias = "EIC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Emirates Insurance"
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.PartnerProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LifecycleState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("StateChangedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("PartnerId", "ProductCode")
                        .IsUnique();

                    b.ToTable("PartnerProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000001"),
                            CompanyCode = "AAI-RBT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LifecycleState = 0,
                            PartnerId = new Guid("b2c3d4e5-0002-0002-0002-000000000001"),
                            ProductCode = 0,
                            StateChangedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000002"),
                            CompanyCode = "AAI-WTQ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LifecycleState = 0,
                            PartnerId = new Guid("b2c3d4e5-0002-0002-0002-000000000001"),
                            ProductCode = 2,
                            StateChangedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000003"),
                            CompanyCode = "DIB-RHN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LifecycleState = 0,
                            PartnerId = new Guid("b2c3d4e5-0002-0002-0002-000000000002"),
                            ProductCode = 1,
                            StateChangedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000004"),
                            CompanyCode = "DIB-MLM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LifecycleState = 0,
                            PartnerId = new Guid("b2c3d4e5-0002-0002-0002-000000000002"),
                            ProductCode = 3,
                            StateChangedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000005"),
                            CompanyCode = "EIC-RBT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LifecycleState = 0,
                            PartnerId = new Guid("b2c3d4e5-0002-0002-0002-000000000003"),
                            ProductCode = 0,
                            StateChangedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000006"),
                            CompanyCode = "EIC-RHN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LifecycleState = 0,
                            PartnerId = new Guid("b2c3d4e5-0002-0002-0002-000000000003"),
                            ProductCode = 1,
                            StateChangedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PortalType")
                        .HasColumnType("int");

                    b.Property<int>("ProductAccessMode")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Code = 0,
                            Description = "Insurance data to ICP",
                            Name = "Rabet",
                            PortalType = 0,
                            ProductAccessMode = 0
                        },
                        new
                        {
                            Code = 1,
                            Description = "Mortgage transactions",
                            Name = "Rhoon",
                            PortalType = 0,
                            ProductAccessMode = 0
                        },
                        new
                        {
                            Code = 2,
                            Description = "Vehicle insurance data",
                            Name = "Wtheeq",
                            PortalType = 1,
                            ProductAccessMode = 0
                        },
                        new
                        {
                            Code = 3,
                            Description = "Motor insurance pricing",
                            Name = "Mulem",
                            PortalType = 1,
                            ProductAccessMode = 0
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LabelPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientCompany")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TrackingNumber");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.SlaPause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PausedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("PausedBusinessHours")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ResumedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SlaTrackerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SlaTrackerId");

                    b.ToTable("SlaPauses");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.SlaTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BusinessHoursElapsed")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Notified75")
                        .HasColumnType("bit");

                    b.Property<bool>("Notified90")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifiedBreach")
                        .HasColumnType("bit");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetBusinessHours")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsActive", "TicketId");

                    b.HasIndex("TicketId", "StageOrder");

                    b.ToTable("SlaTrackers");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.StageDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignedRole")
                        .HasColumnType("int");

                    b.Property<int>("SlaBusinessHours")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<int>("StageType")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "StageOrder")
                        .IsUnique();

                    b.ToTable("StageDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0001-0001-000000000001"),
                            AssignedRole = 2,
                            SlaBusinessHours = 24,
                            StageName = "Legal Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0001-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 16,
                            StageName = "Product Review",
                            StageOrder = 2,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0001-0003-000000000001"),
                            AssignedRole = 4,
                            SlaBusinessHours = 8,
                            StageName = "EA Sign-off",
                            StageOrder = 3,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0002-0001-000000000001"),
                            AssignedRole = 2,
                            SlaBusinessHours = 24,
                            StageName = "Legal Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0002-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 16,
                            StageName = "Product Review",
                            StageOrder = 2,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0002-0003-000000000001"),
                            AssignedRole = 4,
                            SlaBusinessHours = 8,
                            StageName = "EA Sign-off",
                            StageOrder = 3,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0003-0001-000000000001"),
                            AssignedRole = 2,
                            SlaBusinessHours = 24,
                            StageName = "Legal Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0003-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 16,
                            StageName = "Product Review",
                            StageOrder = 2,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0003-0003-000000000001"),
                            AssignedRole = 4,
                            SlaBusinessHours = 8,
                            StageName = "EA Sign-off",
                            StageOrder = 3,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0004-0001-000000000001"),
                            AssignedRole = 2,
                            SlaBusinessHours = 24,
                            StageName = "Legal Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0004-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 16,
                            StageName = "Product Review",
                            StageOrder = 2,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0101-0004-0003-000000000001"),
                            AssignedRole = 4,
                            SlaBusinessHours = 8,
                            StageName = "EA Sign-off",
                            StageOrder = 3,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0101-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0001-0001-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0001-0002-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "Access Provisioning",
                            StageOrder = 2,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0001-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 8,
                            StageName = "API Credential Creation",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0001-0004-000000000001"),
                            AssignedRole = 1,
                            SlaBusinessHours = 0,
                            StageName = "Awaiting UAT Signal",
                            StageOrder = 4,
                            StageType = 3,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0001-0005-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "UAT Sign-off",
                            StageOrder = 5,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0002-0001-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0002-0002-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "Access Provisioning",
                            StageOrder = 2,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0002-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 8,
                            StageName = "API Credential Creation",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0002-0004-000000000001"),
                            AssignedRole = 1,
                            SlaBusinessHours = 0,
                            StageName = "Awaiting UAT Signal",
                            StageOrder = 4,
                            StageType = 3,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0002-0005-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "UAT Sign-off",
                            StageOrder = 5,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0003-0001-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0003-0002-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "Access Provisioning",
                            StageOrder = 2,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0003-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 8,
                            StageName = "API Credential Creation",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0003-0004-000000000001"),
                            AssignedRole = 1,
                            SlaBusinessHours = 0,
                            StageName = "Awaiting UAT Signal",
                            StageOrder = 4,
                            StageType = 3,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0003-0005-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "UAT Sign-off",
                            StageOrder = 5,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0004-0001-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0004-0002-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "Access Provisioning",
                            StageOrder = 2,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0004-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 8,
                            StageName = "API Credential Creation",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0004-0004-000000000001"),
                            AssignedRole = 1,
                            SlaBusinessHours = 0,
                            StageName = "Awaiting UAT Signal",
                            StageOrder = 4,
                            StageType = 3,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0102-0004-0005-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 8,
                            StageName = "UAT Sign-off",
                            StageOrder = 5,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0102-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0001-0001-000000000001"),
                            AssignedRole = 8,
                            SlaBusinessHours = 8,
                            StageName = "Partner Ops Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0001-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Sign-off",
                            StageOrder = 2,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0001-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 8,
                            StageName = "Dev Provisioning",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0001-0004-000000000001"),
                            AssignedRole = 7,
                            SlaBusinessHours = 8,
                            StageName = "Business Provisioning",
                            StageOrder = 4,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0003-0001-000000000001"),
                            AssignedRole = 8,
                            SlaBusinessHours = 8,
                            StageName = "Partner Ops Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0003-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Sign-off",
                            StageOrder = 2,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0003-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 8,
                            StageName = "Dev Provisioning",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0003-0004-000000000001"),
                            AssignedRole = 7,
                            SlaBusinessHours = 8,
                            StageName = "Business Provisioning",
                            StageOrder = 4,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0002-0001-000000000001"),
                            AssignedRole = 8,
                            SlaBusinessHours = 8,
                            StageName = "Partner Ops Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0002-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Sign-off",
                            StageOrder = 2,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0002-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 24,
                            StageName = "Dev Provisioning",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0002-0004-000000000001"),
                            AssignedRole = 7,
                            SlaBusinessHours = 24,
                            StageName = "Business Provisioning",
                            StageOrder = 4,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0002-0005-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 24,
                            StageName = "API Provisioning",
                            StageOrder = 5,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0004-0001-000000000001"),
                            AssignedRole = 8,
                            SlaBusinessHours = 8,
                            StageName = "Partner Ops Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0004-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Sign-off",
                            StageOrder = 2,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0004-0003-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 24,
                            StageName = "Dev Provisioning",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0004-0004-000000000001"),
                            AssignedRole = 7,
                            SlaBusinessHours = 24,
                            StageName = "Business Provisioning",
                            StageOrder = 4,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0004-0005-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 24,
                            StageName = "API Provisioning",
                            StageOrder = 5,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000004")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0005-0001-000000000001"),
                            AssignedRole = 8,
                            SlaBusinessHours = 8,
                            StageName = "Partner Ops Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000005")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0005-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Sign-off",
                            StageOrder = 2,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000005")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0005-0003-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 24,
                            StageName = "API Provisioning",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000005")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0006-0001-000000000001"),
                            AssignedRole = 8,
                            SlaBusinessHours = 8,
                            StageName = "Partner Ops Review",
                            StageOrder = 1,
                            StageType = 0,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000006")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0006-0002-000000000001"),
                            AssignedRole = 3,
                            SlaBusinessHours = 8,
                            StageName = "Product Team Sign-off",
                            StageOrder = 2,
                            StageType = 1,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000006")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0103-0006-0003-000000000001"),
                            AssignedRole = 5,
                            SlaBusinessHours = 24,
                            StageName = "API Provisioning",
                            StageOrder = 3,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0103-0001-0001-000000000006")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0104-0001-0001-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 2,
                            StageName = "Verify & Resolve",
                            StageOrder = 1,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0104-0001-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0104-0002-0001-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 2,
                            StageName = "Verify & Resolve",
                            StageOrder = 1,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0104-0001-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0104-0003-0001-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 2,
                            StageName = "Verify & Resolve",
                            StageOrder = 1,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0104-0001-0001-000000000003")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0104-0004-0001-000000000001"),
                            AssignedRole = 6,
                            SlaBusinessHours = 2,
                            StageName = "Verify & Resolve",
                            StageOrder = 1,
                            StageType = 2,
                            WorkflowDefinitionId = new Guid("d4e5f6a7-0104-0001-0001-000000000004")
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.StageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ReassignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ReassignedToUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("StageLogs");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("int");

                    b.Property<string>("FormData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IssueType")
                        .HasColumnType("int");

                    b.Property<Guid>("PartnerProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProvisioningPath")
                        .HasColumnType("int");

                    b.Property<Guid?>("RejectedTicketRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PartnerProductId");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("CreatedByUserId", "CreatedAt");

                    b.HasIndex("Status", "CurrentStageOrder");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "parankush@tixora.ae",
                            FullName = "Parankush",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar.khalid@tixora.ae",
                            FullName = "Omar Khalid",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hannoun@tixora.ae",
                            FullName = "Hannoun",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "albaha@tixora.ae",
                            FullName = "Albaha",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatima.noor@tixora.ae",
                            FullName = "Fatima Noor",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 4
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khalid.rashed@tixora.ae",
                            FullName = "Khalid Rashed",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 5
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.tariq@tixora.ae",
                            FullName = "Ahmed Tariq",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 6
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "layla.hassan@tixora.ae",
                            FullName = "Layla Hassan",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 7
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vilina.sequeira@tixora.ae",
                            FullName = "Vilina Sequeira",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-00000000000a"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.raeed@tixora.ae",
                            FullName = "Sara Raeed",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-00000000000b"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shayman.ali@tixora.ae",
                            FullName = "Shayman Ali",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 8
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-00000000000c"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@tixora.ae",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$zg9xWkRLs/TGlMdtLiLQ7u9gkpe1uCLYqAJ/HZV5jLnpnmC//19w2",
                            Role = 9
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<int?>("ProvisioningPath")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode", "TaskType", "ProvisioningPath")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("WorkflowDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-0101-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 0,
                            TaskType = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0101-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 1,
                            TaskType = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0101-0001-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 2,
                            TaskType = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0101-0001-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 3,
                            TaskType = 0,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0102-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 0,
                            TaskType = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0102-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 1,
                            TaskType = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0102-0001-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 2,
                            TaskType = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0102-0001-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 3,
                            TaskType = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0103-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 0,
                            ProvisioningPath = 0,
                            TaskType = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0103-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 0,
                            ProvisioningPath = 1,
                            TaskType = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0103-0001-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 1,
                            ProvisioningPath = 0,
                            TaskType = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0103-0001-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 1,
                            ProvisioningPath = 1,
                            TaskType = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0103-0001-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 2,
                            ProvisioningPath = 2,
                            TaskType = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0103-0001-0001-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 3,
                            ProvisioningPath = 2,
                            TaskType = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0104-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 0,
                            TaskType = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0104-0001-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 1,
                            TaskType = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0104-0001-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 2,
                            TaskType = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0104-0001-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ProductCode = 3,
                            TaskType = 3,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Tixora.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany("AuditEntries")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.DelegateApprover", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "DelegateUser")
                        .WithMany()
                        .HasForeignKey("DelegateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.User", "PrimaryUser")
                        .WithMany()
                        .HasForeignKey("PrimaryUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DelegateUser");

                    b.Navigation("PrimaryUser");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Document", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Documents")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipient");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.PartnerProduct", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.Partner", "Partner")
                        .WithMany("PartnerProducts")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.SlaPause", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.SlaTracker", "SlaTracker")
                        .WithMany("Pauses")
                        .HasForeignKey("SlaTrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlaTracker");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.SlaTracker", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany("SlaTrackers")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.StageDefinition", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Stages")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.StageLog", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.User", "ReassignedTo")
                        .WithMany()
                        .HasForeignKey("ReassignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tixora.Domain.Entities.Ticket", "Ticket")
                        .WithMany("StageLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("ReassignedTo");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Tixora.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tixora.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.PartnerProduct", "PartnerProduct")
                        .WithMany("Tickets")
                        .HasForeignKey("PartnerProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tixora.Domain.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("PartnerProduct");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Partner", b =>
                {
                    b.Navigation("PartnerProducts");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.PartnerProduct", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.SlaTracker", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Comments");

                    b.Navigation("Documents");

                    b.Navigation("SlaTrackers");

                    b.Navigation("StageLogs");
                });

            modelBuilder.Entity("Tixora.Domain.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
